### ISSUE TITLE
Train F2-NeRF on your custom data

### ISSUE THREAD

**Issue by jelleopard** [Totoro97/f2-nerf#14]
Generate cameras file:

When I run the command of :python scripts/colmap2poses.py --data_dir ./data/<your-dataset-name>/<your-case-name>
The issues  as follows：
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/F2-NERF/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/xxx/anaconda3/envs/F2-NERF/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/anaconda3/envs/F2-NERF/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxx/f2-nerf/scripts/colmap2poses.py", line 218, in main
    dataset = Dataset(data_dir)
  File "/home/xxx/f2-nerf/scripts/colmap2poses.py", line 137, in __init__
    image_id_to_image_idx[name_to_ids[image_name]] = sorted_image_names.index(image_name)
IndexError: index 372 is out of bounds for axis 0 with size 29
python-BaseException

**Comment by Totoro97** [comment]
Hello, it seems to be a common issue when some images fail to be registered in COLMAP SfM. I would try to address it in the processing when I have time. At this stage you may check you input images and make sure that the images are with rich and sharp visual textures for a successful structure-from-motion.

**Comment by rockywind** [comment]
@Totoro97 
How can I use the pose data to generate the training data?

**Comment by jelleopard** [comment]
Thank you for your reply

**Comment by Khoa-NT** [comment]
Hello @Totoro97, do you have any plan to fix it? COLMAP SfM is always failed on my dataset.
Or can you integrate [hloc](https://github.com/cvg/Hierarchical-Localization) into your code as an alternate option for using COLMAP?

**Comment by WeihongPan** [comment]
> Generate cameras file:
> 
> When I run the command of :python scripts/colmap2poses.py --data_dir ./data// The issues as follows： Traceback (most recent call last): File "/home/xxx/anaconda3/envs/F2-NERF/lib/python3.9/site-packages/click/core.py", line 1055, in main rv = self.invoke(ctx) File "/home/xxx/anaconda3/envs/F2-NERF/lib/python3.9/site-packages/click/core.py", line 1404, in invoke return ctx.invoke(self.callback, **ctx.params) File "/home/xxx/anaconda3/envs/F2-NERF/lib/python3.9/site-packages/click/core.py", line 760, in invoke return __callback(*args, **kwargs) File "/home/xxx/f2-nerf/scripts/colmap2poses.py", line 218, in main dataset = Dataset(data_dir) File "/home/xxx/f2-nerf/scripts/colmap2poses.py", line 137, in **init** image_id_to_image_idx[name_to_ids[image_name]] = sorted_image_names.index(image_name) IndexError: index 372 is out of bounds for axis 0 with size 29 python-BaseException

I solved it by change [https://github.com/Totoro97/f2-nerf/blob/683b7b8326b35b70c8d2a2850a1f794a8ffca010/scripts/colmap2poses.py#LL135C25-L135C25](image_id_to_image_idx) to
`image_id_to_image_idx = np.zeros(len(os.listdir(pjoin(data_dir, "images"))) + 10, dtype=np.int32)`
