### ISSUE TITLE
Is it possible to generate ply file 

### ISSUE THREAD

**Issue by kikirizki** [Totoro97/f2-nerf#23]
Hi thank you for your great work, I saw that the demo is generating sequence of images by interpolating image pose, I wonder if it is possible to generate the 3D object (maybe .ply file) for entire scene instead so we can open it using software like blender.

**Comment by Totoro97** [comment]
Hi, thanks for your interest in this project. Theoretically, it can generate ply files using some techniques like marching cubes, but the mesh quality should not be very good and may have many noises.

**Comment by kikirizki** [comment]
Ok I got it, thank you for your response
