### ISSUE TITLE
what's the physical meaning of oct_idx_start_end and trans_idx in tree node?

### ISSUE THREAD

**Issue by xiepeter** [Totoro97/f2-nerf#25]
In PersSampler module of the code,  oct_idx_start_end appears quite often, wonder the physical meaning of oct_idx_start_end? Is it the volume point in sub grid? And what's the meaning of trans_idx in tree node? to mark a node whether to visited or not? thank u very much~~
![image](https://user-images.githubusercontent.com/15033583/236369128-7c25f151-b1b2-4a9b-a294-8546d8b5193f.png)
![image](https://user-images.githubusercontent.com/15033583/236369183-dbf0db18-a172-41a4-9b36-6dba01f314ab.png)

**Comment by Totoro97** [comment]
Hello, thanks for your interest in this project.  You can assume `oct_idx_start_end` is an array shape of [n_rays, 2], with `oct_interect_idx` they store the information of the intersected octree nodes. For example, this pseudo-code below prints all the intersected octree node index of the ray:
```
for i in range(oct_idx_start_end[ray_idx][0], oct_idx_start_end[ray_idx][1]):
    print(oct_interect_idx[i])
```

**Comment by xiepeter** [comment]
what if a ray intersect several sub_grids, oct_idx_start_end only stores the first and last sub_grid id?
