### ISSUE TITLE
Several paper typos 

### ISSUE THREAD

**Issue by kwea123** [Totoro97/f2-nerf#31]
Fixing these would help better formula understanding:

1.  In Definition 1. in the last sentence, the summation is from i to `n_c` not `n`
2.  In Problem 1. in the last sentence, the summation is from j to `n_p` not `K`
3. What is Figure. 11? It is not described in text.

Thank you.

**Comment by Totoro97** [comment]
Hello, thank you for pointing out that. For Figure 11, we should have described in the discussion about distance alignment, but we wrongly referred to Figure 12. We will fix it.
