### ISSUE TITLE
Failed to reconstruct aerial photography scene

### ISSUE THREAD

**Issue by yzslab** [Totoro97/f2-nerf#44]
Hi,
I have some photos of a building taken by a drone, and can be reconstructed successfully by instant-ngp:
| | |
| ----------- | ----------- |
| ![gym-1](https://github.com/Totoro97/f2-nerf/assets/564361/a3267ce0-453f-4f78-abc6-cd271a6b95e1) | ![gym-2](https://github.com/Totoro97/f2-nerf/assets/564361/a5ac1f49-8cd6-40e9-8340-fc9c3713d637) |

I tried to reconstruct it by F2-NeRF, but found the result full of artifacts (both free.yaml and wanjinyou.yaml):
| RGB | DEPTH | OCT_DEPTH |
| ----------- | ----------- | ----------- |
| ![color_20000_000](https://github.com/Totoro97/f2-nerf/assets/564361/db61df31-31af-4975-9a91-1ef2b2a6a6ba) | ![depth_20000_000](https://github.com/Totoro97/f2-nerf/assets/564361/a554b732-e4ca-4984-9e42-91a3e6651cc4) | ![oct_depth_20000_000](https://github.com/Totoro97/f2-nerf/assets/564361/41ecdf9c-bcd3-415a-8abc-589985ba3681) |
| ![color_20000_040](https://github.com/Totoro97/f2-nerf/assets/564361/bc1d8159-743d-4297-a17e-67a3889cdb14) | ![depth_20000_040](https://github.com/Totoro97/f2-nerf/assets/564361/808cf702-7d4b-40fa-aaa3-a2184a7d3ca5) | ![oct_depth_20000_040](https://github.com/Totoro97/f2-nerf/assets/564361/cb18e2da-9cae-4e0d-8429-f0bace89e9e4) |

Is there any hyperparameters need to be changed for scenes like this?
Thanks.

**Comment by Totoro97** [comment]
It looks too many floaters on the synthesized images. How does the rendered image look like in the training set? You can use `mode=render_all` to render images from all poses.

I would suggest increasing the pts_sampler.near parameter, perhaps to 0.1, as a potential solution for removing the floaters. Additionally, I am exploring methods for the removal of floaters. It would be immensely helpful if you could provide the image set for debugging purposes.

**Comment by yzslab** [comment]
> It looks too many floaters on the synthesized images. How does the rendered image look like in the training set? You can use `mode=render_all` to render images from all poses.
> 
> I would suggest increasing the `pts_sampler.near` parameter, perhaps to `0.1`, as a potential solution for removing the floaters. Additionally, I am exploring methods for the removal of floaters. It would be immensely helpful if you could provide the image set for debugging purposes.

Hi, thanks for your advices. I'm rendering all images now. I will send you my image set to your Outlook email later.

**Comment by yzslab** [comment]
> It looks too many floaters on the synthesized images. How does the rendered image look like in the training set? You can use `mode=render_all` to render images from all poses.
> 
> I would suggest increasing the `pts_sampler.near` parameter, perhaps to `0.1`, as a potential solution for removing the floaters. Additionally, I am exploring methods for the removal of floaters. It would be immensely helpful if you could provide the image set for debugging purposes.

Hi, after rendering training set images, I found some mismatch camera poses between the G.T. image and rendered one:
![20000_403](https://github.com/Totoro97/f2-nerf/assets/564361/26cf88ef-7825-4033-84ac-301be08ffad3)

Seems like it caused by the assumption in [scripts/run.py#L18](https://github.com/Totoro97/f2-nerf/blob/683b7b8326b35b70c8d2a2850a1f794a8ffca010/scripts/run.py#L18) that colmap has registed all image into a single model. My image set has 571 images in total while colmap only registed 529 into the sparse model. So it leds some camera poses mismatch.

I'm trying to fix it and will tell you the result later.
Thanks.

**Comment by yzslab** [comment]
Hi, by putting only the colmap registered images into `image_list.txt`, F2-NeRF can produce a better result now:
| free.yml, 20K iterations |
| -- |
| ![20000_64](https://github.com/Totoro97/f2-nerf/assets/564361/8c96058b-1637-40ce-aa72-06a08bb83e60) |
| ![color_20000_000](https://github.com/Totoro97/f2-nerf/assets/564361/79cf8485-280a-483f-b5d7-f88a3d329a3c) |
| ![color_20000_432](https://github.com/Totoro97/f2-nerf/assets/564361/27d5b7d9-d7f5-4329-bbe1-6d8446eec7ae) |

Here is my modification: https://github.com/yzslab/f2-nerf/commit/5e72c96cba1beb620063c96f2a57b4bbc540cc77. It may be not an elegent solution so I don't make a pull request now.
I have sent the image set download link to your email.

Thanks.
