### ISSUE TITLE
Float blur in render images

### ISSUE THREAD

**Issue by LingyunWang** [Totoro97/f2-nerf#51]
Really appreciate for your important job and share of the project ! I use data captured by Dji sport camera to reconstruct the scene, which are high quality!
  
![color_20000_208](https://github.com/Totoro97/f2-nerf/assets/19383671/44c6f317-ff32-46fd-9c5a-66989de35990)

But recently I move a fly camera around a unbounded scene, the rendered images have float blur!
![color_20000_008](https://github.com/Totoro97/f2-nerf/assets/19383671/e25ca2d4-fc0b-4619-bb98-73391a873859)

I checked the camera poses (as below). Looks like no problem.
![屏幕截图 2023-05-18 182635](https://github.com/Totoro97/f2-nerf/assets/19383671/e13a9d0d-5c29-43b2-9fc8-3549b5d78a4d)

All the data of images and camera poses are available:
https://drive.google.com/file/d/1Zf36hdqAk1NI5u9ucJ7rQs2HBc3i1sIA/view?usp=sharing
Looking forward to paying attention to this issue

**Comment by Totoro97** [comment]
Hi, I guess the main reason is incorrect camera poses. Could try this `cams_meta.npy` [file](https://www.dropbox.com/s/3dfrw89ev99f5ox/cams_meta_hloc.npy?dl=0) and try it again? I obtained it by [hloc](https://github.com/cvg/Hierarchical-Localization) instead of traditional colmap SfM. If the results are better, I will add hloc SfM in this repo. Since the images have some motion blurs, it would be challenging for pose estimation by colmap.

**Comment by LingyunWang** [comment]
> Hi, I guess one of the main causes is incorrect camera poses. Could you try this `cams_meta.npy` [file](https://www.dropbox.com/s/3dfrw89ev99f5ox/cams_meta_hloc.npy?dl=0) and train it again? I obtained it by [hloc](https://github.com/cvg/Hierarchical-Localization) instead of traditional colmap SfM. If the results are better, I will add hloc SfM in this repo. Since the images here have some motion blurs, it would be challenging for pose estimation by colmap.

It bring great imporvement using new camera poses caculated by hloc ! Thank you very much!
 
![color_20000_064](https://github.com/Totoro97/f2-nerf/assets/19383671/b4632367-213e-4ce4-9702-8cf4a5e8ecd0)

![color_20000_008](https://github.com/Totoro97/f2-nerf/assets/19383671/c79d7177-77fc-418d-a5e3-62ac952c6cb2)
