### ISSUE TITLE
Questions about workstations used for this study

### ISSUE THREAD

**Issue by SoninVision** [Totoro97/f2-nerf#58]
First of all, thank you for your great work!

I've been studying NeRF recently and planning to set up my workstation to research NeRF.

So if possible, I would like you to share the information about your workstation's hardware spec that you used during this study. (CPU, RAM capacity, etc.) Not sure, but I found through the paper that you used Nvidia 2080Ti to train the model.

It will be a great help to me.

Thank you again!

**Comment by Totoro97** [comment]
Hi, I tested `f2-nerf` in two platforms, one is with Nvidia RTX 2080ti + Intel Xeon Silver 4114 + 32G memory. Another is Nvidia RTX3080 laptop + AMD Ryzen 9 5900HX + 32G memory.

**Comment by SoninVision** [comment]
Thanks a lot!
