### ISSUE TITLE
Unsupported gpu architecture 'compute_89'

### ISSUE THREAD

**Issue by bruinxiong** [Totoro97/f2-nerf#59]
![image](https://github.com/Totoro97/f2-nerf/assets/3366247/30dc7607-dc00-4e14-b797-df82fb250ee9)

Hi,

is there any solution ?

**Comment by bruinxiong** [comment]
I've solved!

**Comment by dawnchen123** [comment]
@bruinxiong Hi, could you please tell me how to solve this problem

**Comment by LyndzP** [comment]
@dawnchen123 Hi, in may case, it was solved when i upgrade cuda version 11.6 to 11.8

**Comment by bruinxiong** [comment]
@dawnchen123 @LyndzP Sorry for late reply. Yes, that's a solution.
