### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Tobe2d** [Totoro97/f2-nerf#6]
Any plans on supporting windows 11?

Pleaseeeeeeeeeeeeee

**Comment by Totoro97** [comment]
Hello, currently we do not plan to support Windows in the near future. You may use something like WSL to run F2-nerf on Windows. Sorry for any inconvenience caused.

**Comment by Tobe2d** [comment]
Thanks for the reply @Totoro97 

I will test it out on WSL2 ;-)
