### ISSUE TITLE
bad result in kitti360

### ISSUE THREAD

**Issue by h8c2** [Totoro97/f2-nerf#65]
Thanks for your great work. I was working on training f2-nerf in kitti360.
However, the result was really bad.
![image](https://github.com/Totoro97/f2-nerf/assets/37017782/1da9a498-ea24-47bb-820e-a3163f7d0424)
(the train view of seq 2013_05_28_drive_0018_sync)
I first converted the cam0_to_world.txt from kitti360 to cam_meta.npy and use the wanjinyou_big.yaml to train my model.
Although I select a few part of the dataset and train it again, the result was not successful.
![image](https://github.com/Totoro97/f2-nerf/assets/37017782/a177b6bc-6e98-4c9a-86ee-7c23b8ade08b)
with test image psnr around 10
I was wondering if I made some mistakes. It is appreciate if you could give me some advice.

**Comment by Totoro97** [comment]
Hi, thanks for your interest. I do not have this sequence of data. Could you share this sequence of images for the debugging? Thanks!

**Comment by h8c2** [comment]
thanks for your kind reply. I have uploaded the data to google drive, the processed dictionary stores the train format and other dicts are the raw data from 2013_05_28_drive_0018_sync kitti360. https://drive.google.com/drive/folders/1dOxm-HF07kcvOoUf2eRzxK2SWdlkbfWD?usp=sharing

**Comment by h8c2** [comment]
Thank you very much for your kind and useful reply. I have checked the data again and found that the previous sequence is one-tenth the frame rate of a normal sequence. I turn to another sequence 2013_05_28_drive_0010_sync and train with about 100 frames. The results are great.
![image](https://github.com/Totoro97/f2-nerf/assets/37017782/a9c5dde1-6778-4c2c-9f07-29036d272736)
![image](https://github.com/Totoro97/f2-nerf/assets/37017782/347213ba-dd67-4a1e-9ce8-df8f2e59c08d)
Thanks again for providing such an effective way to train NeRF in the real, unbound scene.

**Comment by qhdqhd** [comment]
@h8c2 Thank you!

**Comment by h8c2** [comment]
> 

Hi, I have tested the first data(0018) with both mono and stereo perspective cameras, since the view is very sparse. Both settings failed. The second data is monocular. I suppose the problem may be caused by the construction of the octree since the octree requires the certain number of cameras to split and build warp function.

**Comment by ckLibra** [comment]
> Thank you very much for your kind and useful reply. I have checked the data again and found that the previous sequence is one-tenth the frame rate of a normal sequence. I turn to another sequence 2013_05_28_drive_0010_sync and train with about 100 frames. The results are great. ![image](https://user-images.githubusercontent.com/37017782/243987916-a9c5dde1-6778-4c2c-9f07-29036d272736.png) ![image](https://user-images.githubusercontent.com/37017782/243988027-347213ba-dd67-4a1e-9ce8-df8f2e59c08d.png) Thanks again for providing such an effective way to train NeRF in the real, unbound scene.

@h8c2 Hi, May I ask you the train/test split for kitti360 and your final PSNR? Do you follow the default split in code for 100 frames? Currently I use a 80 frames trajectory on kitti and its average PSNR for test 8 frames are 22.5. 
 I also wonder what is its performance like when we apply the official kitti360 novel view synthesis which has fewer training images.

**Comment by ckLibra** [comment]
@Totoro97 Thanks for your reply! It really helps.

**Comment by chuong98** [comment]
> For your reference, F2-NeRF can be successfully trained by `wanjinyou.yaml` (with `factor=1`) on this example data from the Kitti dataset: https://www.dropbox.com/s/v9avgr9akvjcprx/kitti_sample.zip?dl=0

Hi @Totoro97, thanks for releasing the illustrated example for Kitti. I can reproduce f2-nerf on this dataset. However, when I tried to generate the dataset.db using both:
`scripts/local_hloc_and_resize.sh` and `scripts/local_colmap_and_resize.sh`, I can't generate good Camera Pose for estimation. 
Do we need to run specific version of ColMap or Hloc, or do I need to change any parameters? Thanks so much
