### ISSUE TITLE
Any suggestions on training on  custom dataset that generates Nan

### ISSUE THREAD

**Issue by jelleopard** [Totoro97/f2-nerf#70]
Thanks for your great work. I was working on training f2-nerf in my custom dataset.
However, generated Nan. The follow up has always been Nan

Iter:     50 PSNR: 3.18 NRays: 29936 OctSamples: 9.0 Samples: 8.8 MeaningfulSamples: 8.8 IPS: 28.5 LR: 0.0005
Iter:    100 PSNR: 3.24 NRays: 29648 OctSamples: 9.0 Samples: 8.8 MeaningfulSamples: 8.8 IPS: 26.0 LR: 0.0010
Iter:    150 PSNR: 9.61 NRays: 29360 OctSamples: 9.0 Samples: 8.9 MeaningfulSamples: 8.9 IPS: 24.6 LR: 0.0015
Iter:    200 PSNR: 11.12 NRays: 29072 OctSamples: 9.0 Samples: 9.0 MeaningfulSamples: 9.0 IPS: 25.4 LR: 0.0020
Iter:    250 PSNR: 11.29 NRays: 28768 OctSamples: 9.0 Samples: 9.1 MeaningfulSamples: 9.1 IPS: 24.8 LR: 0.0025
Iter:    300 PSNR: 11.35 NRays: 28480 OctSamples: 9.0 Samples: 9.2 MeaningfulSamples: 9.2 IPS: 25.3 LR: 0.0030
Iter:    350 PSNR: 14.84 NRays: 29280 OctSamples: 9.0 Samples: 9.3 MeaningfulSamples: 8.9 IPS: 25.9 LR: 0.0035
Iter:    400 PSNR: 16.46 NRays: 29056 OctSamples: 9.0 Samples: 9.4 MeaningfulSamples: 9.0 IPS: 25.8 LR: 0.0040
Iter:    450 PSNR: 16.68 NRays: 28576 OctSamples: 9.0 Samples: 9.5 MeaningfulSamples: 9.2 IPS: 26.1 LR: 0.0045
Iter:    500 PSNR: 16.78 NRays: 28032 OctSamples: 9.0 Samples: 9.6 MeaningfulSamples: 9.4 IPS: 26.1 LR: 0.0050
Iter:    550 PSNR: 16.83 NRays: 27616 OctSamples: 9.0 Samples: 9.7 MeaningfulSamples: 9.5 IPS: 25.8 LR: 0.0055
Iter:    600 PSNR: 16.85 NRays: 27200 OctSamples: 9.0 Samples: 9.8 MeaningfulSamples: 9.6 IPS: 26.5 LR: 0.0060
Iter:    650 PSNR: 16.96 NRays: 26832 OctSamples: 9.0 Samples: 9.9 MeaningfulSamples: 9.8 IPS: 26.3 LR: 0.0065
Iter:    700 PSNR: 16.99 NRays: 26464 OctSamples: 9.0 Samples: 10.0 MeaningfulSamples: 9.9 IPS: 26.8 LR: 0.0070
Iter:    750 PSNR: 16.98 NRays: 26112 OctSamples: 9.0 Samples: 10.1 MeaningfulSamples: 10.0 IPS: 26.5 LR: 0.0075
Iter:    800 PSNR: 17.04 NRays: 25824 OctSamples: 9.0 Samples: 10.2 MeaningfulSamples: 10.2 IPS: 26.2 LR: 0.0080
Iter:    850 PSNR: 17.09 NRays: 25536 OctSamples: 9.0 Samples: 10.3 MeaningfulSamples: 10.3 IPS: 26.7 LR: 0.0085
Iter:    900 PSNR: 17.06 NRays: 25280 OctSamples: 9.0 Samples: 10.5 MeaningfulSamples: 10.4 IPS: 27.0 LR: 0.0090
Iter:    950 PSNR: 17.10 NRays: 25024 OctSamples: 9.0 Samples: 10.6 MeaningfulSamples: 10.5 IPS: 26.8 LR: 0.0095
Iter:   1000 PSNR: 17.11 NRays: 24736 OctSamples: 9.0 Samples: 10.7 MeaningfulSamples: 10.6 IPS: 27.4 LR: 0.0100
n_nodes_before is value 81
n_nodes_compacted is value 81
tree_nodes_.size() is value 81
n_nodes_before is value 81
n_nodes_compacted is value 81
tree_nodes_.size() is value 81
Iter:   1050 PSNR: 17.11 NRays: 24480 OctSamples: 9.0 Samples: 10.8 MeaningfulSamples: 10.7 IPS: 27.1 LR: 0.0100
Iter:   1100 PSNR: 17.17 NRays: 24288 OctSamples: 9.0 Samples: 10.9 MeaningfulSamples: 10.8 IPS: 27.2 LR: 0.0100
Iter:   1150 PSNR: 17.14 NRays: 24032 OctSamples: 9.0 Samples: 11.0 MeaningfulSamples: 10.9 IPS: 27.3 LR: 0.0100
Iter:   1200 PSNR: 17.17 NRays: 23856 OctSamples: 9.0 Samples: 11.2 MeaningfulSamples: 11.0 IPS: 27.3 LR: 0.0100
Iter:   1250 PSNR: 17.18 NRays: 23632 OctSamples: 9.0 Samples: 11.3 MeaningfulSamples: 11.1 IPS: 27.3 LR: 0.0100
Iter:   1300 PSNR: 17.21 NRays: 23472 OctSamples: 9.0 Samples: 11.4 MeaningfulSamples: 11.2 IPS: 27.5 LR: 0.0100
Iter:   1350 PSNR: 17.22 NRays: 23296 OctSamples: 9.0 Samples: 11.5 MeaningfulSamples: 11.2 IPS: 26.8 LR: 0.0100
Iter:   1400 PSNR: 17.16 NRays: 23120 OctSamples: 9.0 Samples: 11.7 MeaningfulSamples: 11.3 IPS: 26.4 LR: 0.0100
Iter:   1450 PSNR: 17.16 NRays: 22928 OctSamples: 9.0 Samples: 11.8 MeaningfulSamples: 11.4 IPS: 27.2 LR: 0.0100
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!
Nan!

**Comment by Totoro97** [comment]
Hello, may I ask how many images were used for the training? Additionally, the number of point samples for each ray appears unusually low. Typically, in such cases, I would suspect that the images were not registered in the correct poses.

**Comment by jelleopard** [comment]
Thanks for your reply. I have resolved this problem，that is because of the bound uncorrected

**Comment by jywu511** [comment]
@jelleopard Hi, I meet the same problem. Could you please tell me more about what is "bound uncorrected" and how you solved it? Thanks very much!
