### ISSUE TITLE
what is first_oct_disp？

### ISSUE THREAD

**Issue by Bin-ze** [Totoro97/f2-nerf#79]
Sorry to bother you, I didn't understand what is first_oct_disp.
@Totoro97

**Comment by Totoro97** [comment]
Hi, it is the disparity value (inverted distance) of the intersection point of the first intersected octree node from the camera viewpoint.

**Comment by Bin-ze** [comment]
What is the difference between him and depth parallax? In f2-nerf, the octree is used to divide the subspace area, so what is the physical meaning of the ray passing through the octree node for the first time? Can you talk about this process in detail? I'm a xiaocaiji, sorry sorry
