### ISSUE TITLE
export point cloud in orginal space 

### ISSUE THREAD

**Issue by Bin-ze** [Totoro97/f2-nerf#80]
I try to use f2-nerf to export point cloud, the method is very simple, just map the depth value into 3d space:
> Tensor point = rays_o.to(torch::kCPU) + rays_d.to(torch::kCPU) * pred_depth;

but I found that the exported point cloud has some distortion problems, which is also normal, if the sample is trained in warping space , how do I map the point cloud to Euclidean space?

**Comment by Bin-ze** [comment]
I have another question, what is the range of the point cloud prediction result? Is it in a [-1,1] box?

**Comment by meriemjabri** [comment]
so did you manage to predict depth ? or do you mean *pred_disps?

**Comment by Bin-ze** [comment]
yes， f2-nerf can predict depth , so can export point cloud, but depth in warping space(), you can check these:
https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/exporter/exporter_utils.py
Another point is that how to filter points that are far away needs to be considered, which affects the quality of the point cloud

**Comment by Bin-ze** [comment]
@Totoro97 shuaige, could you tell me how to export point cloud?

**Comment by JingyuanHu** [comment]
@Bin-ze Hi, 你找到解决原始空间内，点云输出的方法了吗

**Comment by maliksyria** [comment]
@Bin-ze I'm having exactly the same issue. Generated disparity has issues in distortion, Have you managed to solve that?

**Comment by zZH1222hui** [comment]
> @龙猫97帅哥，你能告诉我如何导出点云吗？

Hi,Have you found the method of exporting point cloud?
