### ISSUE TITLE
mipnerf360 garden result is poor

### ISSUE THREAD

**Issue by tianxiaguixin002** [Totoro97/f2-nerf#88]
I trained the code on mipnerf360 garden data whth following scripts:

python scripts/llff2poses.py --data_dir=./data/mip-360/garden

python scripts/run.py --config-name=nerf-360 \
dataset_name=./data/mip-360 \
case_name=garden mode=train

I have modify the factor=4 in nerf-360.yaml,  when finish training, the log show:
.....
n_nodes_compacted is value 735094
tree_nodes_.size() is value 735094
Iter:  19050 PSNR: 20.47 NRays:  8080 OctSamples: 46.0 Samples: 119.9 MeaningfulSamples: 32.4 IPS: 23.2 LR: 0.0011
Iter:  19100 PSNR: 20.44 NRays:  8048 OctSamples: 45.9 Samples: 119.7 MeaningfulSamples: 32.5 IPS: 22.6 LR: 0.0010
Iter:  19150 PSNR: 20.41 NRays:  8080 OctSamples: 45.9 Samples: 119.6 MeaningfulSamples: 32.4 IPS: 23.2 LR: 0.0010
Iter:  19200 PSNR: 20.42 NRays:  8080 OctSamples: 46.0 Samples: 119.6 MeaningfulSamples: 32.4 IPS: 22.7 LR: 0.0010
Iter:  19250 PSNR: 20.41 NRays:  8096 OctSamples: 45.9 Samples: 119.5 MeaningfulSamples: 32.3 IPS: 22.8 LR: 0.0010
Iter:  19300 PSNR: 20.44 NRays:  8096 OctSamples: 45.9 Samples: 119.3 MeaningfulSamples: 32.4 IPS: 22.9 LR: 0.0010
Iter:  19350 PSNR: 20.45 NRays:  8128 OctSamples: 45.8 Samples: 119.2 MeaningfulSamples: 32.3 IPS: 22.9 LR: 0.0010
Iter:  19400 PSNR: 20.48 NRays:  8048 OctSamples: 45.7 Samples: 119.1 MeaningfulSamples: 32.5 IPS: 22.7 LR: 0.0010
Iter:  19450 PSNR: 20.46 NRays:  8080 OctSamples: 45.7 Samples: 119.2 MeaningfulSamples: 32.4 IPS: 22.9 LR: 0.0010
Iter:  19500 PSNR: 20.44 NRays:  8096 OctSamples: 45.7 Samples: 119.1 MeaningfulSamples: 32.4 IPS: 22.8 LR: 0.0010
Iter:  19550 PSNR: 20.48 NRays:  8128 OctSamples: 45.7 Samples: 119.0 MeaningfulSamples: 32.2 IPS: 23.1 LR: 0.0010
Iter:  19600 PSNR: 20.47 NRays:  8128 OctSamples: 45.6 Samples: 118.9 MeaningfulSamples: 32.2 IPS: 22.9 LR: 0.0010
Iter:  19650 PSNR: 20.46 NRays:  8144 OctSamples: 45.5 Samples: 118.8 MeaningfulSamples: 32.2 IPS: 22.8 LR: 0.0010
Iter:  19700 PSNR: 20.51 NRays:  8144 OctSamples: 45.6 Samples: 119.0 MeaningfulSamples: 32.1 IPS: 23.1 LR: 0.0010
Iter:  19750 PSNR: 20.46 NRays:  8144 OctSamples: 45.6 Samples: 118.9 MeaningfulSamples: 32.2 IPS: 22.8 LR: 0.0010
Iter:  19800 PSNR: 20.46 NRays:  8128 OctSamples: 45.5 Samples: 118.8 MeaningfulSamples: 32.3 IPS: 23.1 LR: 0.0010
Iter:  19850 PSNR: 20.45 NRays:  8160 OctSamples: 45.5 Samples: 118.8 MeaningfulSamples: 32.2 IPS: 23.3 LR: 0.0010
Iter:  19900 PSNR: 20.48 NRays:  8160 OctSamples: 45.5 Samples: 118.5 MeaningfulSamples: 32.1 IPS: 23.1 LR: 0.0010
Iter:  19950 PSNR: 20.54 NRays:  8176 OctSamples: 45.4 Samples: 118.5 MeaningfulSamples: 32.1 IPS: 23.3 LR: 0.0010
Iter:  20000 PSNR: 20.48 NRays:  8160 OctSamples: 45.4 Samples: 118.5 MeaningfulSamples: 32.1 IPS: 0.8 LR: 0.0010
Train done, test.
0: 10.378842
8: 10.334309
16: 12.714293
24: 8.00071
32: 7.812619
40: 9.196725
48: 12.872265
56: 11.860228
64: 12.492895
72: 13.710265
80: 11.093293
88: 11.43869
96: 14.673181
104: 16.585175
112: 14.040527
120: 10.907651
128: 12.12698
136: 15.01075
144: 12.956245
152: 12.072407
160: 14.45992
168: 9.386232
176: 11.397999
184: 12.814769
Mean psnr: 12.014041

The test psnr is 12? it is a bad result, where is the problem ? thank you.

**Comment by Bin-ze** [comment]
I think there should be a misalignment between the image and the pose. You can check whether the image_list.txt in the dataset directory is misaligned with the image, or check whether the rendered image does not match the GT. I hope it can help you !

**Comment by tianxiaguixin002** [comment]
Thank
