### ISSUE TITLE
Rendering voxel artefacts, what could be the cause

### ISSUE THREAD

**Issue by htlpt** [Totoro97/f2-nerf#94]
I was building on Win11, torch 2.0.1, CUDA 11.8, RTX4090
training the example ngp_fox, seeing voxel artifacts, could it be the platform, the GPU(mix-precision ?), or just torch version..
![20000_001](https://github.com/Totoro97/f2-nerf/assets/25838728/90aa2540-a972-40a5-ab89-214cf30b31ef)

**Comment by htlpt** [comment]
![image](https://github.com/Totoro97/f2-nerf/assets/25838728/f6fb10b0-7b0c-4368-b044-eefdaf94af90)
I noticed the NaN in the training, possibly FP16 overflow?

**Comment by htlpt** [comment]
```
Train done, test.
0: 17.752699
8: 12.5911665
16: 12.909588
24: 9.543803
32: 11.67271
40: 12.495184
48: 11.199245
Mean psnr: 12.594914
```
low PSNR of course...

**Comment by htlpt** [comment]
It's just the unstablility of CUDA on Windows, WSL2 runs just fine...

**Comment by pmp-ya** [comment]
Hello, I'm currently facing the same issue as you, voxel-like noise appearing in novel images in Windows. I followed your experience and reconfigured the environment on WSL, but I still encountered the same voxel-like noise. Could you please share your configuration on WSL? I'm really struggling with this.
My configuration is as follows:
1. Win11, torch 1.10, CUDA 11.8, RTX4080;
2. WSL, ubuntu20, torch 1.10, CUDA 11.8, RTX4080;
3. The configuration I used is the default wanjinyou.conf; (I changed "factor:2" to "factor:1" as it caused the colors variable to be infinite. Details can be found in #20.)
If you could provide any feedback, I would be extremely grateful.
The following two images are generated by my WSL and Win11 respectively 
![20000_000](https://github.com/user-attachments/assets/9eaed82c-819a-46da-893f-999d03f7ee5a)
![20000_000](https://github.com/user-attachments/assets/f216581b-0af6-4d8b-8c35-a82ec565cbaa)
