### ISSUE TITLE
Add LaplaceDensity to substitute original density, but psnr drops a lot

### ISSUE THREAD

**Issue by xiepeter** [Totoro97/f2-nerf#95]
I added  LaplaceDensity to substitute original density, but it seems psnr dropped a lot. I wonder whether it caused by sampling or I need a larger mlp network?
<img width="790" alt="image" src="https://github.com/Totoro97/f2-nerf/assets/15033583/4a157e39-8091-443e-97dc-e4e3526dbd19">

**Comment by maliksyria** [comment]
Have you managed with this? has it improved the work of F2 ?
